---
- name: Add group
  hosts: all
  tasks:
    - name: Add group to RedHat Family
      when: ansible_os_family == "RedHat"
      user:
        name: "{{ item }}"
      with_items:
        - managers
        - sales
        - marketing
        - IT
        - NOC
        - admins
